In [1]:
from pathlib import Path
from torch.utils.data import Dataset
import numpy as np
import pandas as pd

In [2]:
XCOLS = ['input_orientation_yaw', 'input_orientation_pitch', 'input_orientation_roll',
         'acceleration_x', 'acceleration_y', 'acceleration_z']
YCOLS = ['input_orientation_yaw', 'input_orientation_pitch', 'input_orientation_roll']

In [3]:
train_files = sorted(list(Path('data/1116').glob('*scene3_0.csv')))
test_files = sorted(list(Path('data/1116').glob('*scene3_1.csv')))

In [4]:
window_size = 120
stride = 1

# Make Train Dataset

In [5]:
X_train = []
Y_train = []
for f in train_files:
    print(f)
    csv = pd.read_csv(f)
    i = 0
    while i <= len(csv) - window_size * 2:
        X_train.append(csv.iloc[i:i + window_size][XCOLS].to_numpy())
        Y_train.append(csv.iloc[i + window_size + 18][YCOLS].to_numpy())
        i += stride

data/1116/user1_scene3_0.csv
data/1116/user2_scene3_0.csv
data/1116/user3_scene3_0.csv
data/1116/user4_scene3_0.csv
data/1116/user5_scene3_0.csv
data/1116/user6_scene3_0.csv
data/1116/user7_scene3_0.csv


In [6]:
np.savez_compressed(f'data/1116/train-win_{window_size}-GAN2.npz', X=X_train, Y=Y_train)

In [7]:
Y_train[2].shape

(3,)

In [8]:
X_train[0].shape

(120, 6)

# Make Test Dataset

In [9]:
X_train = []
Y_train = []
for f in test_files:
    print(f)
    csv = pd.read_csv(f)
    i = 0
    while i <= len(csv) - window_size * 2:
        X_train.append(csv.iloc[i:i + window_size][XCOLS].to_numpy())
        Y_train.append(csv.iloc[i + window_size + 18][YCOLS].to_numpy())
        i += stride

data/1116/user1_scene3_1.csv
data/1116/user2_scene3_1.csv
data/1116/user3_scene3_1.csv
data/1116/user4_scene3_1.csv
data/1116/user5_scene3_1.csv
data/1116/user6_scene3_1.csv
data/1116/user7_scene3_1.csv


In [10]:
np.savez_compressed(f'data/1116/test-win_{window_size}-GAN2.npz', X=X_train, Y=Y_train)

In [11]:
X_train[0].shape

(120, 6)

# Mean, Variance 구하기

In [12]:
data1 = np.load('data/1116/train-win_120-GAN2.npz')
data2 = np.load('data/1116/test-win_120-GAN2.npz')

In [13]:
data = np.concatenate([data1['X'], data2['X']])

In [14]:
data.mean(axis=(0, 1))

array([-2.66218441,  7.47775972,  0.05826464,  0.22432731,  9.58267249,
       -1.03175692])

In [15]:
data.std(axis=(0, 1))

array([25.34557277,  8.91109505,  3.36267677,  0.7035975 ,  0.27769154,
        1.53018414])

In [29]:
data.mean(axis=(0, 1))

array([-1.66273531,  8.21902937,  0.52039963,  0.30343397,  9.56865156,
       -1.16180179])

In [30]:
data.std(axis=(0, 1))

array([24.18274048,  8.82230789,  3.15849637,  0.67317067,  0.27715342,
        1.51914225])